### ISSUE TITLE
TypeError: float expected at most 1 argument, got 2

### ISSUE THREAD

**Issue by Megachip** [garbled1/homeassistant_ecowitt#27]
```
2020-10-25 12:07:38 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
resp = await task
File "/usr/local/lib/python3.8/site-packages/pyecowitt/ecowitt.py", line 262, in handler
weather_data = self.convert_units(data_copy)
File "/usr/local/lib/python3.8/site-packages/pyecowitt/ecowitt.py", line 163, in convert_units
data["windspdkmh_avg10m"] = float(data["windspdmph_avg10m"]
TypeError: float expected at most 1 argument, got 2
```

**Comment by garbled1** [comment]
This might be fixed in latest update, can you check 0.3.1 please?

**Comment by garbled1** [comment]
This should be fixed in 0.4

**Comment by cpuks** [comment]
This bug still exists in 0.4:
Logger: aiohttp.server
Source: /usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py:355
First occurred: 17:29:37 (1 occurrences)
Last logged: 17:29:37

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/pyecowitt/ecowitt.py", line 272, in handler
    weather_data = self.convert_units(data_copy)
  File "/usr/local/lib/python3.8/site-packages/pyecowitt/ecowitt.py", line 165, in convert_units
    data["windspdkmh_avg10m"] = float(data["windspdmph_avg10m"]
TypeError: float expected at most 1 argument, got 2

**Comment by garbled1** [comment]
yep.  ugh.

**Comment by garbled1** [comment]
Actually, I'm going to close this as a duplicate of #28 .  I'm tracking the fix in that issue.
